### ISSUE TITLE
compile errors

### ISSUE THREAD

**Issue by ghost** [djyde/WebShell#63] opened 2016-08-21 18:24 UTC
NSTimer.scheduledTimerWithTimeInterval(NSTimeInterval(timeAsInt!), target: self, selector: #selector(ViewController.flashScreenNow), userInfo: nil, repeats: false)
            }

Expected ',' separator
Expected expression in list of expressions

I get like 61 errors like those when executing Product > Archive

**Comment by 0xWDG** [comment] 2016-08-21 18:47
Are you using Xcode beta (version 8.0).
Then Yes, I'll now it but we didn't optimize all the code for Swift 3.
Since there were between beta 1, and beta 6 a lot of major changes in the swift 3 compiler.

Please report the Xcode version and the build number.
Second are you using Swift 2.x or Swift 3?

**Comment by 0xWDG** [comment] 2016-08-21 20:29
If you are using Xcode-Beta 8.0.

Please remove the WebShell directory.
then open the terminal and run this command.
`git clone https://github.com/djyde/WebShell.git -b Swift30`
This will clone the (experimental) Swift 3.0 version of WebShell

If this works for you please report it to us.
Please refer to #61 for all the Swift 3 issues

**Comment by ghost** [comment] 2016-08-21 21:04
Well I installed Xcode 7.3.1 and it compiled ok so I will not investigate further.

I have an other question though. I set the app home URL to "https://console.aws.amazon.com/dynamodb/" and if I try to log in AWS it opens  Safari.

**Comment by 0xWDG** [comment] 2016-08-21 21:18
Hi,

Are you sure that in the configuration the following is set as i show here

```
    // Open target=_blank in a new screen? (Default: false)
    "openInNewScreen": false,
```

p.s. i'm getting a weird error if i want to enable cookies (swift 3.0 version, i run Sierra so i can not use 7.3.1. anymore)

And since, debugging does not work yet on Swift 3, i cannot check that.
Sorry about that.

**Comment by 0xWDG** [comment] 2016-08-21 21:20
- if there is a problem, with using it please open an issue, I close this one, because the "Swift 3" issue is #61 and the problem you describing is a new problem.

Thanks for using WebShell!

**Comment by ghost** [comment] 2016-08-21 21:20
yes it is set to false

**Closed as completed** 2016-08-21 21:20 UTC
Labels: question

**Comment by 0xWDG** [comment] 2016-08-21 21:22
Please make a bug report using this manual. https://github.com/djyde/WebShell/blob/master/contributing.md

---

# Contributing / Making issues

If you experience problems with a specific web(app)

_(visible by running via Xcode or by running with parameter -debug true)_

Please use the `Debug` -> `Report an issue on this page` button, so we know the full url.

![Debug - Report an issue on this page](http://m83.imgup.net/ReportIssuf311.png)

When pressed the report your **default** webbrowser will open and redirect you to the github issues page, with some pre-filled fields, then you can enter what exactly the problem is.

**Comment by 0xWDG** [comment] 2016-08-21 21:22
- Closing topic.
